# Generated by Django 4.1.3 on 2022-12-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0002_alter_create_account_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verify',
            name='Code',
            field=models.IntegerField(),
        ),
    ]
