# Generated by Django 4.1.3 on 2023-01-01 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0003_alter_verify_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLimgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Images', models.ImageField(upload_to='Photos/%y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Txtbx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Pages.slimgs')),
            ],
        ),
    ]
