# Generated by Django 4.1.3 on 2023-01-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0004_slimgs_txtbx'),
    ]

    operations = [
        migrations.AddField(
            model_name='txtbx',
            name='Text',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
