# Generated by Django 4.1.3 on 2023-01-01 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0005_txtbx_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='txtbx',
            name='Image',
        ),
        migrations.DeleteModel(
            name='SLimgs',
        ),
        migrations.DeleteModel(
            name='Txtbx',
        ),
    ]
