# Generated by Django 4.2.1 on 2023-05-24 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0006_remove_txtbx_image_delete_slimgs_delete_txtbx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Create_Account',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Reenter_Email',
        ),
        migrations.DeleteModel(
            name='Reset_password',
        ),
        migrations.DeleteModel(
            name='Verify',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='Feedback',
            new_name='fdbk',
        ),
    ]
