# Generated by Django 4.2.1 on 2023-05-24 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0007_delete_create_account_delete_login_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='fdbk',
            new_name='text',
        ),
    ]
