# Generated by Django 4.2.1 on 2023-05-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Translations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='txtbx',
            old_name='Image',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='txtbx',
            old_name='Text',
            new_name='txt',
        ),
        migrations.AlterField(
            model_name='myuuidmodel',
            name='TranslationBox',
            field=models.ImageField(upload_to='im'),
        ),
        migrations.AlterField(
            model_name='slimgs',
            name='Images',
            field=models.ImageField(upload_to='im'),
        ),
    ]
