# Generated by Django 4.2.1 on 2023-05-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Translations', '0002_rename_image_txtbx_img_rename_text_txtbx_txt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='images/')),
                ('letter', models.CharField(max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='txtbx',
            name='txt',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
