# Generated by Django 4.2.1 on 2023-05-24 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Translations', '0003_image_alter_txtbx_txt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUUIDModel',
        ),
        migrations.RemoveField(
            model_name='txtbx',
            name='img',
        ),
        migrations.DeleteModel(
            name='Slimgs',
        ),
        migrations.DeleteModel(
            name='Txtbx',
        ),
    ]
